version: '3.8'

networks:
  monitoring:
    driver: bridge

services:
  redis:
    image: 'redis'
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - monitoring